spring.application.name=smartfileorganizer

# Server Port
server.port=8080

# Neon DB Postgres Properties
spring.datasource.url=jdbc:postgresql://ep-late-math-atz9tvgo-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fEVAzNd0F9vx
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limit
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# JWT Secret
# Generate a strong 256-bit secret key (e.g. at least 32 characters long)
jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTMyLWNoYXJzLWxvbmc=
jwt.expirationMs=86400000

# File Storage Directory
file.upload-dir=uploads
